INSERT INTO trains.city (city_region, city_name) VALUES ('Moulay Abdallah', 'Morocco');
INSERT INTO trains.city (city_region, city_name) VALUES ('Dangcalan', 'Philippines');
INSERT INTO trains.city (city_region, city_name) VALUES ('Esperanza', 'Philippines');
INSERT INTO trains.city (city_region, city_name) VALUES ('Mansilingan', 'Philippines');
INSERT INTO trains.city (city_region, city_name) VALUES ('Czarna', 'Poland');
INSERT INTO trains.city (city_region, city_name) VALUES ('Gremyachinsk', 'Russia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Kandete', 'Tanzania');
INSERT INTO trains.city (city_region, city_name) VALUES ('Ishqoshim', 'Tajikistan');
INSERT INTO trains.city (city_region, city_name) VALUES ('Biryulëvo', 'Russia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Ōi', 'Japan');
INSERT INTO trains.city (city_region, city_name) VALUES ('Beyla', 'Guinea');
INSERT INTO trains.city (city_region, city_name) VALUES ('São João Nepomuceno', 'Brazil');
INSERT INTO trains.city (city_region, city_name) VALUES ('Pesisir', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Grugul', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Gaptsakh', 'Russia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Cibangun Tengah', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Numeto', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Xiaqiao', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('An Nāşirīyah', 'Iraq');
INSERT INTO trains.city (city_region, city_name) VALUES ('Nova Kakhovka', 'Ukraine');
INSERT INTO trains.city (city_region, city_name) VALUES ('Longhe', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Qili', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Älvdalen', 'Sweden');
INSERT INTO trains.city (city_region, city_name) VALUES ('Sumberdadi', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Ribeira Grande', 'Cape Verde');
INSERT INTO trains.city (city_region, city_name) VALUES ('Oeiras', 'Brazil');
INSERT INTO trains.city (city_region, city_name) VALUES ('Tuanfeng', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Bato', 'Philippines');
INSERT INTO trains.city (city_region, city_name) VALUES ('Měcholupy', 'Czech Republic');
INSERT INTO trains.city (city_region, city_name) VALUES ('Khabarovsk', 'Russia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Batugede Kulon', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Shuanghe', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('San Esteban', 'Philippines');
INSERT INTO trains.city (city_region, city_name) VALUES ('Katsina', 'Nigeria');
INSERT INTO trains.city (city_region, city_name) VALUES ('Sidorejo', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Azeitão', 'Portugal');
INSERT INTO trains.city (city_region, city_name) VALUES ('Ghāt', 'Libya');
INSERT INTO trains.city (city_region, city_name) VALUES ('Castainço', 'Portugal');
INSERT INTO trains.city (city_region, city_name) VALUES ('Muslyumovo', 'Russia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Mekarsari', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Asarum', 'Sweden');
INSERT INTO trains.city (city_region, city_name) VALUES ('Newark', 'United States');
INSERT INTO trains.city (city_region, city_name) VALUES ('Ḩabūr', 'Yemen');
INSERT INTO trains.city (city_region, city_name) VALUES ('Agana Heights Village', 'Guam');
INSERT INTO trains.city (city_region, city_name) VALUES ('Wuhu', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Kalbugan', 'Philippines');
INSERT INTO trains.city (city_region, city_name) VALUES ('Sanom', 'Thailand');
INSERT INTO trains.city (city_region, city_name) VALUES ('Shingū', 'Japan');
INSERT INTO trains.city (city_region, city_name) VALUES ('Gävle', 'Sweden');
INSERT INTO trains.city (city_region, city_name) VALUES ('Avignon', 'France');
INSERT INTO trains.city (city_region, city_name) VALUES ('Arujá', 'Brazil');
INSERT INTO trains.city (city_region, city_name) VALUES ('Tongjiang', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Pingshan', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Padasono', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Al Ḩudaydah', 'Yemen');
INSERT INTO trains.city (city_region, city_name) VALUES ('Kladi', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Lyubimets', 'Bulgaria');
INSERT INTO trains.city (city_region, city_name) VALUES ('Mollepampa', 'Peru');
INSERT INTO trains.city (city_region, city_name) VALUES ('Beishidian', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Dengtang', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Maseru', 'Lesotho');
INSERT INTO trains.city (city_region, city_name) VALUES ('Dijon', 'France');
INSERT INTO trains.city (city_region, city_name) VALUES ('Suai', 'East Timor');
INSERT INTO trains.city (city_region, city_name) VALUES ('Espinal', 'Colombia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Jastrzębia Góra', 'Poland');
INSERT INTO trains.city (city_region, city_name) VALUES ('Qobustan', 'Azerbaijan');
INSERT INTO trains.city (city_region, city_name) VALUES ('Vranje', 'Serbia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Panite', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Thị Trấn Na Hang', 'Vietnam');
INSERT INTO trains.city (city_region, city_name) VALUES ('Huambalpa', 'Peru');
INSERT INTO trains.city (city_region, city_name) VALUES ('Stepove', 'Ukraine');
INSERT INTO trains.city (city_region, city_name) VALUES ('Svrljig', 'Serbia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Veldhoven', 'Netherlands');
INSERT INTO trains.city (city_region, city_name) VALUES ('Pau', 'France');
INSERT INTO trains.city (city_region, city_name) VALUES ('Gontar', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Ubonratana', 'Thailand');
INSERT INTO trains.city (city_region, city_name) VALUES ('Nova Varoš', 'Serbia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Gaoping', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Haymā’', 'Oman');
INSERT INTO trains.city (city_region, city_name) VALUES ('Yimamu', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Zhlobin', 'Belarus');
INSERT INTO trains.city (city_region, city_name) VALUES ('Longbo', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Grimshaw', 'Canada');
INSERT INTO trains.city (city_region, city_name) VALUES ('Jagodina', 'Serbia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Simeykyne', 'Ukraine');
INSERT INTO trains.city (city_region, city_name) VALUES ('Paulpietersburg', 'South Africa');
INSERT INTO trains.city (city_region, city_name) VALUES ('Mampong', 'Ghana');
INSERT INTO trains.city (city_region, city_name) VALUES ('Balong Wetan', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Koryukivka', 'Ukraine');
INSERT INTO trains.city (city_region, city_name) VALUES ('Milówka', 'Poland');
INSERT INTO trains.city (city_region, city_name) VALUES ('Filabusi', 'Zimbabwe');
INSERT INTO trains.city (city_region, city_name) VALUES ('Tân Việt', 'Vietnam');
INSERT INTO trains.city (city_region, city_name) VALUES ('Pochinki', 'Russia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Embarcación', 'Argentina');
INSERT INTO trains.city (city_region, city_name) VALUES ('Oroin Xibe', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Vágia', 'Greece');
INSERT INTO trains.city (city_region, city_name) VALUES ('Zhuangke', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Calape', 'Philippines');
INSERT INTO trains.city (city_region, city_name) VALUES ('Pontes', 'Portugal');
INSERT INTO trains.city (city_region, city_name) VALUES ('Marignane', 'France');
INSERT INTO trains.city (city_region, city_name) VALUES ('Nāṟay', 'Afghanistan');
INSERT INTO trains.city (city_region, city_name) VALUES ('Pesnica pri Mariboru', 'Slovenia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Sundsvall', 'Sweden');
INSERT INTO trains.city (city_region, city_name) VALUES ('Avlónas', 'Greece');
INSERT INTO trains.city (city_region, city_name) VALUES ('Hwado', 'South Korea');
INSERT INTO trains.city (city_region, city_name) VALUES ('Afareaitu', 'French Polynesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Murovanoye', 'Ukraine');
INSERT INTO trains.city (city_region, city_name) VALUES ('Santa Cruz', 'Philippines');
INSERT INTO trains.city (city_region, city_name) VALUES ('Lom Sak', 'Thailand');
INSERT INTO trains.city (city_region, city_name) VALUES ('Krasae Sin', 'Thailand');
INSERT INTO trains.city (city_region, city_name) VALUES ('Tagum', 'Philippines');
INSERT INTO trains.city (city_region, city_name) VALUES ('Bonneuil-sur-Marne', 'France');
INSERT INTO trains.city (city_region, city_name) VALUES ('Sa Pá', 'Vietnam');
INSERT INTO trains.city (city_region, city_name) VALUES ('Al Ḩusayn', 'Yemen');
INSERT INTO trains.city (city_region, city_name) VALUES ('Simpang', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Paseyan', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('El Puerto', 'Dominican Republic');
INSERT INTO trains.city (city_region, city_name) VALUES ('Leer', 'South Sudan');
INSERT INTO trains.city (city_region, city_name) VALUES ('Bente', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Roanoke', 'United States');
INSERT INTO trains.city (city_region, city_name) VALUES ('Bayt Sīrā', 'Palestinian Territory');
INSERT INTO trains.city (city_region, city_name) VALUES ('Maiorca', 'Portugal');
INSERT INTO trains.city (city_region, city_name) VALUES ('Bergen', 'Norway');
INSERT INTO trains.city (city_region, city_name) VALUES ('San Rafael', 'Mexico');
INSERT INTO trains.city (city_region, city_name) VALUES ('Kalipare', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Gvardeysk', 'Russia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Sophia Antipolis', 'France');
INSERT INTO trains.city (city_region, city_name) VALUES ('Outeiro de Polima', 'Portugal');
INSERT INTO trains.city (city_region, city_name) VALUES ('Acherítou', 'Cyprus');
INSERT INTO trains.city (city_region, city_name) VALUES ('Danderyd', 'Sweden');
INSERT INTO trains.city (city_region, city_name) VALUES ('Jiguaní', 'Cuba');
INSERT INTO trains.city (city_region, city_name) VALUES ('Murmashi', 'Russia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Vodyane', 'Ukraine');
INSERT INTO trains.city (city_region, city_name) VALUES ('Orange', 'France');
INSERT INTO trains.city (city_region, city_name) VALUES ('Nueva Guadalupe', 'El Salvador');
INSERT INTO trains.city (city_region, city_name) VALUES ('Mirošov', 'Czech Republic');
INSERT INTO trains.city (city_region, city_name) VALUES ('As Sawdā', 'Syria');
INSERT INTO trains.city (city_region, city_name) VALUES ('Osa', 'Russia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Jiuhe', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Yahe', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Jiangyin', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Bhalil', 'Morocco');
INSERT INTO trains.city (city_region, city_name) VALUES ('Mosquée', 'Morocco');
INSERT INTO trains.city (city_region, city_name) VALUES ('San Miguel', 'Mexico');
INSERT INTO trains.city (city_region, city_name) VALUES ('Tanjungbatu', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Salavat', 'Russia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Nar''yan-Mar', 'Russia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Pimenta Bueno', 'Brazil');
INSERT INTO trains.city (city_region, city_name) VALUES ('Praia da Tocha', 'Portugal');
INSERT INTO trains.city (city_region, city_name) VALUES ('Matingain', 'Philippines');
INSERT INTO trains.city (city_region, city_name) VALUES ('Ořechov', 'Czech Republic');
INSERT INTO trains.city (city_region, city_name) VALUES ('Sterling', 'United States');
INSERT INTO trains.city (city_region, city_name) VALUES ('Laško', 'Slovenia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Kharkhorin', 'Mongolia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Nancun', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Vizal San Pablo', 'Philippines');
INSERT INTO trains.city (city_region, city_name) VALUES ('La Tola', 'Colombia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Yashio-shi', 'Japan');
INSERT INTO trains.city (city_region, city_name) VALUES ('Krynice', 'Poland');
INSERT INTO trains.city (city_region, city_name) VALUES ('Богданци', 'Macedonia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Zblewo', 'Poland');
INSERT INTO trains.city (city_region, city_name) VALUES ('Tatebal', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Shatoujiao', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Yatsushiro', 'Japan');
INSERT INTO trains.city (city_region, city_name) VALUES ('Höshööt', 'Mongolia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Dembéni', 'Comoros');
INSERT INTO trains.city (city_region, city_name) VALUES ('Requena', 'Peru');
INSERT INTO trains.city (city_region, city_name) VALUES ('Matangshan', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Panggunguni', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Rongelap', 'Marshall Islands');
INSERT INTO trains.city (city_region, city_name) VALUES ('Namballe', 'Peru');
INSERT INTO trains.city (city_region, city_name) VALUES ('Penápolis', 'Brazil');
INSERT INTO trains.city (city_region, city_name) VALUES ('Changle', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Saint-Quentin-en-Yvelines', 'France');
INSERT INTO trains.city (city_region, city_name) VALUES ('Puerto Guzmán', 'Colombia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Sơn Hà', 'Vietnam');
INSERT INTO trains.city (city_region, city_name) VALUES ('Carregal', 'Portugal');
INSERT INTO trains.city (city_region, city_name) VALUES ('Sunfang', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Geshan', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Stockholm', 'Sweden');
INSERT INTO trains.city (city_region, city_name) VALUES ('Jining', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Matanog', 'Philippines');
INSERT INTO trains.city (city_region, city_name) VALUES ('Murça', 'Portugal');
INSERT INTO trains.city (city_region, city_name) VALUES ('Xian’an', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Paraíso', 'Portugal');
INSERT INTO trains.city (city_region, city_name) VALUES ('Suvorov', 'Russia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Yangpu', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Várzea', 'Portugal');
INSERT INTO trains.city (city_region, city_name) VALUES ('Aughrim', 'Ireland');
INSERT INTO trains.city (city_region, city_name) VALUES ('Sidirókastro', 'Greece');
INSERT INTO trains.city (city_region, city_name) VALUES ('Taishihe', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Fucheng', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Orekhovo-Borisovo Severnoye', 'Russia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Karangkedawung', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Longjumeau', 'France');
INSERT INTO trains.city (city_region, city_name) VALUES ('Purwodadi', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Balun', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Costeira do Pirajubae', 'Brazil');
INSERT INTO trains.city (city_region, city_name) VALUES ('Pondokkaha Kelod', 'Indonesia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Khlevnoye', 'Russia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Foso', 'Ghana');
INSERT INTO trains.city (city_region, city_name) VALUES ('Robonkon', 'Philippines');
INSERT INTO trains.city (city_region, city_name) VALUES ('Turanj', 'Croatia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Bachaquero', 'Venezuela');
INSERT INTO trains.city (city_region, city_name) VALUES ('Gotse Delchev', 'Bulgaria');
INSERT INTO trains.city (city_region, city_name) VALUES ('Kirs', 'Russia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Xiping', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Majiang', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Silae', 'Philippines');
INSERT INTO trains.city (city_region, city_name) VALUES ('Hanyuan', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Municipio de Copacabana', 'Colombia');
INSERT INTO trains.city (city_region, city_name) VALUES ('Águas Vermelhas', 'Brazil');
INSERT INTO trains.city (city_region, city_name) VALUES ('Město', 'Czech Republic');
INSERT INTO trains.city (city_region, city_name) VALUES ('Luoluopu', 'China');
INSERT INTO trains.city (city_region, city_name) VALUES ('Vahdat', 'Tajikistan');
INSERT INTO trains.city (city_region, city_name) VALUES ('Parachinar', 'Pakistan');
INSERT INTO trains.city (city_region, city_name) VALUES ('Pochayiv', 'Ukraine');
