insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Runolfsson-Schamberger', 'Moulay Abdallah', 'Morocco', 59);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Reynolds Inc', 'Dangcalan', 'Philippines', 58);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Howell and Sons', 'Esperanza', 'Philippines', 31);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Schinner LLC', 'Mansilingan', 'Philippines', 72);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Braun-Barton', 'Czarna', 'Poland', 63);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Auer, Gulgowski and Bergnaum', 'Gremyachinsk', 'Russia', 21);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Leannon, Stokes and Kulas', 'Kandete', 'Tanzania', 47);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Cummerata Inc', 'Ishqoshim', 'Tajikistan', 13);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Kunze LLC', 'Biryulëvo', 'Russia', 60);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Towne, Ferry and Terry', 'Ōi', 'Japan', 96);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Vandervort-Hahn', 'Beyla', 'Guinea', 13);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Kling LLC', 'São João Nepomuceno', 'Brazil', 91);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Bradtke, Macejkovic and Fahey', 'Pesisir', 'Indonesia', 8);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Gorczany, Funk and Dickens', 'Grugul', 'Indonesia', 82);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Cummerata Group', 'Gaptsakh', 'Russia', 57);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Halvorson, Buckridge and Fritsch', 'Cibangun Tengah', 'Indonesia', 37);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Hessel-Collier', 'Numeto', 'Indonesia', 48);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Bernier-McDermott', 'Xiaqiao', 'China', 7);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Keeling, Farrell and Balistreri', null, null, 71);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Johnson-McDermott', 'An Nāşirīyah', 'Iraq', 59);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('O''Kon, Watsica and Kreiger', 'Nova Kakhovka', 'Ukraine', 30);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Schmeler-Schuppe', 'Longhe', 'China', 10);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Parker-Gulgowski', 'Qili', 'China', 87);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Bergstrom, Kerluke and Ritchie', 'Älvdalen', 'Sweden', 52);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Schoen-Williamson', 'Sumberdadi', 'Indonesia', 5);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Harvey Group', 'Ribeira Grande', 'Cape Verde', 83);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Renner Inc', 'Oeiras', 'Brazil', 49);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Kunde-Lesch', 'Tuanfeng', 'China', 7);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('McKenzie LLC', 'Bato', 'Philippines', 36);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Trantow LLC', 'Měcholupy', 'Czech Republic', 22);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Robel LLC', 'Khabarovsk', 'Russia', 72);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Herzog, Batz and Boyle', 'Batugede Kulon', 'Indonesia', 49);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Glover-Rutherford', 'Shuanghe', 'China', 86);
insert into trains.station (station_name, city_region, city_name, number_of_tracks) values ('Kreiger-Pfannerstill', 'San Esteban', 'Philippines', 14);
