insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (1, '1/21/2022', '5/28/2022', 'Runolfsson-Schamberger', 'Kreiger-Pfannerstill', 45);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (2, '2/2/2022', '5/30/2022', 'Reynolds Inc', 'Glover-Rutherford', 214);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (3, '2/14/2022', '5/19/2022', 'Howell and Sons', 'Herzog, Batz and Boyle', 289);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (4, '12/26/2021', '1/8/2022', 'Schinner LLC', 'Harvey Group', 327);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (5, '1/7/2022', '1/23/2022', 'Braun-Barton', 'Hessel-Collier', 299);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (6, '10/6/2022', '1/28/2022', 'Auer, Gulgowski and Bergnaum', 'Cummerata Inc', 7);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (7, '5/14/2022', '7/24/2022', 'Leannon, Stokes and Kulas', 'Hessel-Collier', 209);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (8, '7/18/2022', '2/17/2022', 'Cummerata Inc', 'Towne, Ferry and Terry', 146);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (9, '6/2/2022', '4/2/2022', 'Kunze LLC', 'Gorczany, Funk and Dickens', 456);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (10, '8/14/2022', '4/12/2022', 'Towne, Ferry and Terry', 'Kunze LLC', 407);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (11, '2/22/2022', '7/6/2022', 'Vandervort-Hahn', 'Schmeler-Schuppe', 184);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (12, '11/25/2021', '8/11/2022', 'Kling LLC', 'Cummerata Group', 41);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (13, '4/18/2022', '9/9/2022', 'Bradtke, Macejkovic and Fahey', 'Halvorson, Buckridge and Fritsch', 456);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (14, '1/31/2022', '9/10/2022', 'Gorczany, Funk and Dickens', 'Parker-Gulgowski', 485);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (15, '3/6/2022', '5/27/2022', 'Cummerata Group', 'Gaptsakh', 'McKenzie LLC', 120);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (16, '11/24/2021', '3/18/2022', 'Halvorson, Buckridge and Fritsch', 'Bergstrom, Kerluke and Ritchie', 136);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (17, '6/21/2022', '10/1/2022', 'Hessel-Collier', 'Runolfsson-Schamberger', 239);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (18, '8/5/2022', '5/16/2022', 'Bernier-McDermott', 'Howell and Sons', 467);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (19, '1/29/2022', '9/12/2022', 'Keeling, Farrell and Balistreri', 'Schinner LLC', 54);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (20, '5/26/2022', '5/27/2022', 'Johnson-McDermott', 'Reynolds Inc', 467);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (21, '1/4/2022', '8/5/2022', 'O''Kon, Watsica and Kreiger', 'Cummerata Group', 450);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (22, '7/11/2022', '1/22/2022', 'Schmeler-Schuppe', 'O''Kon, Watsica and Kreiger', 142);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (23, '7/28/2022', '9/9/2022', 'Parker-Gulgowski', 'Trantow LLC', 117);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (24, '11/11/2021', '3/30/2022', 'Bergstrom, Kerluke and Ritchie', 'Robel LLC', 185);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (25, '6/16/2022', '10/2/2022', 'Schoen-Williamson', 'Harvey Group', 443);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (26, '3/14/2022', '6/28/2022', 'Harvey Group', 'McKenzie LLC', 18);
insert into trains.connection (connected_id, departure, arrival, from_station, to_station, train_nr) values (27, '6/16/2022', '10/31/2021', 'Renner Inc', 'Trantow LLC', 131);
